### ISSUE TITLE
new topic naming does not fit to version 1.0 behavior

### ISSUE THREAD

**Issue by hi-ko** [zulip/zulip-redmine-plugin#21]
Unfortunately in version>= 2.0 the naming for the topic changed from project name to ticket subject. Using version 1.0 we had a clean structure in zulip having a top level project as stream name and the lower level project name as topic. Now the structure is completely confused because for every ticket in _any_ subproject a new topic is created which does not fit in the existing structure.
So we have to roll back to version 1.0 and fix the structure manually in the zulip database.

Fix should be to make stream _and_ topic configurable where the value should support variables or should be a LOV like topic: "$project_name".

**Comment by hi-ko** [comment]
@felipebatista,
in our [fork](https://github.com/ecm4u/zulip-redmine-plugin) I added the project name in the message to replace zulip's message subject in the locale yml. If others prefer ticket subject instead best would be to add a config param in the plugin to select between project name and issue subject which should be evaluated in the issue_patch.rb.

**Comment by hi-ko** [comment]
amazing - thank you! you'll get feedback asap ...

**Comment by hi-ko** [comment]
Hi @felipebatista,

when I try to install the 3.1-alpha1 branch I get the following exception when running `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`:
````
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddSubjectsPatternSettings < ActiveRecord::Migration[4.2]
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:528:in `inherited'
/opt/redmine/plugins/redmine_zulip/db/migrate/20191015152900_add_subjects_pattern_settings.rb:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:986:in `load_migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:982:in `migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1350:in `use_transaction?'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1342:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:504:in `up'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:491:in `block in migrate'
/opt/redmine/lib/redmine/plugin.rb:490:in `each'
/opt/redmine/lib/redmine/plugin.rb:490:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddSubjectsPatternSettings < ActiveRecord::Migration[4.2]
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:528:in `inherited'
/opt/redmine/plugins/redmine_zulip/db/migrate/20191015152900_add_subjects_pattern_settings.rb:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:986:in `load_migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:982:in `migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1350:in `use_transaction?'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1342:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:504:in `up'
/var/lib/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:491:in `block in migrate'
/opt/redmine/lib/redmine/plugin.rb:490:in `each'
/opt/redmine/lib/redmine/plugin.rb:490:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
````

**Comment by hi-ko** [comment]
when updating an issue I now get:
````
Completed 500 Internal Server Error in 103ms (ActiveRecord: 17.6ms)

NoMethodError (private method `zulip_settings' called for #<Issue:0x000055dab310a778>):

plugins/redmine_zulip/lib/redmine_zulip/issue_patch.rb:86:in `block (2 levels) in <module:IssuePatch>'
app/controllers/issues_controller.rb:552:in `save_issue_with_child_records'
app/controllers/issues_controller.rb:169:in `update'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
````

**Comment by felipebatista** [comment]
hello @hi-ko sorry for this, please try version **3.1-alpha2** and let me know

**Comment by hi-ko** [comment]
very cool. That did it!
What is the mimik having all the config values in redmine plugin config and in projects config? project config overwrites global config?

**Comment by hi-ko** [comment]
should be covered in the readme:
admin/plugins/redmin_zulip defines defaults
which could be overwritten in the projects zulip config tab

**Comment by felipebatista** [comment]
@hi-ko, do you think the description in **3.1-beta1** README is clear enough? if not, what change would you do to make it so?

thank you very much

**Comment by hi-ko** [comment]
@felipebatista, I'm very sorry. I overlooked the changes you already made in the README.md
absolutely clear - no changes required.
thanks again.
